# Generated by Django 3.2.7 on 2021-10-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_seance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Seance',
        ),
        migrations.AddField(
            model_name='films',
            name='gen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='films.genres'),
        ),
    ]
